repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff (lint)
        entry: ruff check --output-format=github .
        language: python
        types: [python]
        pass_filenames: false