name: Ruff

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .
        env:
          RUFF_FAIL_ON_ERROR: true

      - name: Run Ruff with fixes
        run: ruff check . --fix
        env:
          RUFF_FAIL_ON_ERROR: true

      - name: Run Ruff with unsafe fixes
        run: ruff check . --fix --unsafe-fixes
        env:
          RUFF_FAIL_ON_ERROR: true

      - name: Check for remaining errors
        run: |
          echo "Checking for remaining Ruff errors..."
          ruff check .
          if [ $? -ne 0 ]; then
            echo " Ruff found errors after fixes. Please fix them before merging."
            exit 1
          fi
        env:
          RUFF_FAIL_ON_ERROR: true
